config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tweets, only: [:index, :new, :create, :destroy]
  resources :users, only: [:show] do
    resources :followers, only: [:create, :destroy]
  end

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :user
  belongs_to :followed_by, class_name: 'User'

  validates :followed_by_id, uniqueness: { scope: :user_id, message: 'Already following'}
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :followers, dependent: :destroy
  has_many :tweets, dependent: :destroy
  has_many :following, class_name: 'Follower', foreign_key: 'followed_by_id'

  validates :username, presence: true, uniqueness: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
  end

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || tweets_path
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_follower, only: :destroy

  def create
    current_user.following.create(user: @user)
    redirect_to user_path(@user)
  end

  def destroy
    @follower.destroy
    redirect_to user_path(@user)
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_follower
    @follower = current_user.following.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def index
    following_ids = current_user.following.pluck(:user_id)
    following_ids << current_user.id
    @tweets = Tweet.where(user_id: following_ids).order(created_at: :desc)
  end

  def new
    @tweet = current_user.tweets.new
  end

  def create
    @tweet = current_user.tweets.new(tweet_params)

    if @tweet.save
      redirect_to tweets_path, notice: 'Tweet created'
    else
      flash[:error] = 'Error'
      render :new
    end
  end

  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
    redirect_to tweets_path, notice: 'Tweet deleted'
  end

  private

  def tweet_params
    params.require(:tweet).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  def show
    @followers = @user.followers
    @following = @user.following
    @follower = @followers.find_by(followed_by_id: current_user.id)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Welcome to Twitter Like App!</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterLikeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/header'%>
    <div class="container">

      <% if notice %>
        <div class="alert alert-success" role="alert">
          <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-warning" role="alert">
          <%= alert %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="#">Twitter Like App</a>
    <% if user_signed_in? %>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item <%= controller_name == 'tweets' ? 'active' : '' %>">
          <%= link_to 'Tweets', tweets_path, class: "nav-link" %>
        </li>

      </ul>
      <ul class="navbar-nav my-2 my-lg-0">
        <li class="nav-item active">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      </ul>
    <% else %>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      </ul>
      <ul class="navbar-nav my-2 my-lg-0">
        <li class="nav-item <%= controller_name == 'sessions' ? 'active' : '' %>">
          <%= link_to 'Sign in', user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= controller_name == 'registrations' ? 'active' : '' %>">
          <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/tweets/_tweet.html.erb
<div class="d-flex w-100 justify-content-between">
  <h6 class="mb-1"><%= link_to tweet.user.username, user_path(tweet.user) %></h6>
  <small><%= tweet.created_at.strftime('%x') %></small>
</div>
<p class="mb-1"><%= tweet.body%></p>
<small>
  <% if tweet.user == current_user %>
    <%= link_to 'delete', tweet_path(tweet), method: :delete %>
  <% end %>
</small>

app/views/tweets/index.html.erb
<%= link_to 'new tweet', new_tweet_path %>
<table>
  <tbody>
    <div class="list-group">
          <%= render @tweets %>
    </div>


  </tbody>
</table>

app/views/tweets/new.html.erb
<%= form_for @tweet do |f| %>
  <%= f.text_area :body, rows: 8 %>
  <%= f.submit %>
<% end %>

app/views/users/_follower.html.erb
<li>
  <%= link_to follower.followed_by.username, user_path(follower.followed_by) %>
</li>

app/views/users/_following.html.erb
<li>
  <%= link_to following.user.username, user_path(following.user) %>
</li>

app/views/users/show.html.erb
<h3><%= @user.username %></h3>
<% if @follower %>
  <%= link_to 'Unfollow', user_follower_path(@user, @follower), method: :delete %>
<% else %>
  <% if current_user != @user %>
    <%= link_to 'Follow', user_followers_path(@user), method: :post %>
  <% end %>
<% end %>
<table>
  <thead>
    <tr>
      <th>Followers</th>
      <th>Following</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <ul>
          <%= render partial: 'users/follower', collection: @followers%>
        </ul>
      </td>
      <td>
        <ul>
          <%= render partial: 'users/following', collection: @following%>
        </ul>
      </td>
    </tr>
  </tbody>
</table>
<h4></h4>